# Generated by Django 4.2.7 on 2025-09-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250912_1245'),
    ]

    operations = [
    ]
