# Generated by Django 4.2.7 on 2025-09-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250912_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
